[workspace]
members = ["d2fps", "d2interface", "bin_patch", "bin_patch_mac", "num"]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
debug = false
panic = "abort"
lto = "fat"
codegen-units = 1
